
mindmap
  root((Y3API Player))
    Navbar
     App Logo 
     Search Bar  
      Searcharea
      Search Icon
    SideBar
      Catergories
      Copyrigth @ Github 2023
    Feed View
      Heading with template literal


   root((API))
    fetchFromAPI
     1. define the BASE_URL
     2. define the API_KEY
     3. define the fetchFromAPI function
     4. takes in a query
     5. returns a promise
     

